#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme 
title: UiPath Automation Cloud | Studio Web: First line of defense from ticket scalpers 
description: False
show_downloads: False
theme: jekyll-theme-minimal
